config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # devise users method
  devise_for :users, path: 'users', controllers: {
    sessions: 'users/sessions', registrations: 'users/registrations'
  }, path_prefix: 'new'
  devise_scope :user do
    get 'new/user/:id', to: 'users/registrations#show'
  end
  # making /dashboard the root for authenticated users
  authenticated :user do
    root 'dashboard#index', as: :authenticated_root
  end
  resources :books
  post '/books/:id/borrow', to: 'books#borrow', as: 'borrow_book'
  post '/books/:id/returnbook', to: 'books#returnbook', as: 'returnbook_book'
  # users managing methods used by secretaries
  resources :users, only: %i[index show edit destroy update]

  # courses managing methods
  get '/courses/enrollable', to: 'courses#enrollable'
  resources :courses do
    resources :materials, only: %i[index show destroy new create]
    resources :enrollments, only: :index
    get 'enrollment', to: 'enrollments#show'
    post 'enrollment/:id', to: 'enrollments#add'
    delete 'enrollment/:id', to: 'enrollments#destroy'
  end
  get 'courses/student/:id', to: 'courses#enrolled'
  get 'auth/google_oauth2_drive/callback', to: 'omniauth_callbacks#google_oauth2_drive'

  # Menus
  get '/menus/indexAll', to: 'menus#indexAll'
  get '/reservations', to: 'reservations#index'
  resources :menus do
    # Reservations
    get '/reservations/newGuest', to: 'reservations#newGuest'
    resources :reservations
  end

  # Forms
  resources :forms do
    get 'showResult', to: 'forms#showResult'
  end

  resources :notifications
  post '/notifications/:id/change_status', to: 'notifications#change_status', as: 'change_status_notifications'

  resources :events

  # courses managing methods
  get '/courses/enrollable', to: 'courses#enrollable'
  resources :courses do
    resources :materials, only: %i[index show destroy new create]
    resources :enrollments, only: :index
    get 'enrollment', to: 'enrollments#show'
    post 'enrollment/:id', to: 'enrollments#add'
    delete 'enrollment/:id', to: 'enrollments#destroy'
  end
  get 'courses/student/:id', to: 'courses#enrolled'
  get 'auth/google_oauth2_drive/callback', to: 'omniauth_callbacks#google_oauth2_drive'
  # root for non authenticated users
  root 'home#index'
  resources :menus, only: [:show]
  get '/auth/google_oauth2/callback', to: 'omniauth_callbacks#google_oauth2'
  get 'auth/failure', to: 'omniauth_callbacks#failure'
  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
end

app/models/book.rb
# frozen_string_literal: true

class Book < ApplicationRecord
  validates_presence_of :title
  validates_presence_of :author
  validates_presence_of :description
  belongs_to :owner, class_name: 'Student'
  belongs_to :current_owner, class_name: 'Student'
end

app/models/canteen.rb
# frozen_string_literal: true

# canteen user
class Canteen < User
  acts_as_user roles: :canteen

  has_many :menus, dependent: :delete_all
  has_many :forms, dependent: :delete_all
end

app/models/course.rb
# frozen_string_literal: true

# course model
class Course < ApplicationRecord
  validates_presence_of :name
  validates_presence_of :begin_year
  validates_presence_of :end_year
  has_and_belongs_to_many :students, join_table: 'enrollments'
  before_destroy {students.clear}
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/form.rb
class Form < ApplicationRecord
  validates_presence_of :dateStart
  validates_presence_of :dateEnd

  belongs_to :canteen
end

app/models/menu.rb
# menu model
class Menu < ApplicationRecord
  validates_presence_of :date
  validates_presence_of :mealType
  
  belongs_to :canteen
  has_many :reservations, dependent: :delete_all
end

app/models/notification.rb
class Notification < ApplicationRecord
    validates_presence_of :title
    validates_presence_of :description

    enum status:{active: 1,archived:0}
end

app/models/official_event.rb
class OfficialEvent < Event
    belongs_to :creator,class_name: 'Secretary' #chi lo crea
end

app/models/reservation.rb
# menu reservations
class Reservation < ApplicationRecord
  validates_presence_of :student
  validates_presence_of :menu

  belongs_to :student
  belongs_to :menu
end

app/models/secretary.rb
# frozen_string_literal: true

# secretary user
class Secretary < User
  acts_as_user roles: :secretary
end

app/models/student.rb
# frozen_string_literal: true

# student user
class Student < User
  acts_as_user roles: :student

  has_many :reservations, dependent: :delete_all
  has_many :owned_books, class_name: 'Book', foreign_key: 'owner_id', dependent: :delete_all
  has_many :borrowed_books, class_name: 'Book', foreign_key: 'current_owner_id', dependent: :delete_all
  has_and_belongs_to_many :courses, join_table: 'enrollments'
  before_destroy {courses.clear}
end

app/models/token.rb
# frozen_string_literal: true

require 'net/http'
require 'json'

class Token < ApplicationRecord
  validates_presence_of :access_token
  validates_presence_of :refresh_token
  validates_presence_of :expires_at
  def to_params
    { 'refresh_token' => refresh_token,
      'client_id' => ENV['Google_Client_Id'],
      'client_secret' => ENV['Google_Client_Secret'],
      'grant_type' => 'refresh_token' }
  end

  def request_token_from_google
    url = URI('https://accounts.google.com/o/oauth2/token')
    Net::HTTP.post_form(url, to_params)
  end

  def refresh!
    response = request_token_from_google
    data = JSON.parse(response.body)
    update_attributes(
      access_token: data['access_token'],
      expires_at: Time.now + data['expires_in'].to_i.seconds
    )
  end

  def expired?
    expires_at < Time.now
  end

  def fresh_token
    refresh! if expired?
    access_token
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  validates_presence_of :first_name
  validates_presence_of :last_name
  validates_presence_of :username
  validates_presence_of :type
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data['email']).first

    # Creating student if they don't exist
    user ||= User.create(first_name: data['first_name'],
                         last_name: data['last_name'],
                         username: data['email'].split('@')[0],
                         email: data['email'],
                         password: Devise.friendly_token[0, 20], type: 'Student')
    user
  end
end

app/controllers/dashboard_controller.rb
# frozen_string_literal: true

# noinspection RailsParamDefResolve
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def index
  end
  
end

app/helpers/books_helper.rb
# frozen_string_literal: true

module BooksHelper
end

app/helpers/courses_helper.rb
# frozen_string_literal: true

module CoursesHelper
end

app/helpers/dashboard_helper.rb
# frozen_string_literal: true

module DashboardHelper
end

app/helpers/forms_helper.rb
module FormsHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/meeting_helper.rb
module MeetingHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/dashboard/index.html.haml
%h2 #{current_user.username.capitalize}'s Dashboard

- if current_user.instance_of? Secretary
  = link_to 'Manage Users', users_path
  %br
  = link_to 'Manage Courses', courses_path
  %br
  = link_to 'Calendar',events_path

  - unless Token.all.any?
    %br
    = link_to 'Authenticate uCollege Drive Account', '/auth/google_oauth2_drive'

- if current_user.instance_of? Student
  = link_to 'Courses', "courses/student/#{current_user.id}"
  %br
  = link_to 'Books', books_path(current_user)
  %br
  = link_to 'Canteen',  reservations_path
  %br
  = link_to 'Calendar', events_path
  %br
  = link_to 'Notifications', notifications_path

- if current_user.instance_of? Canteen
  = link_to 'View menus', menus_path
  %br
  = link_to 'Add menus', new_menu_path
  %br
  = link_to 'List of all menus',  menus_indexAll_path
  %br
  = link_to 'Add questionnaire', new_form_path
  %br
  = link_to 'View info of questionnaires', forms_path
  -#= %h3 'view reservations of the day'

%br
= link_to "About  #{current_user.username}", "/new/user/#{current_user.id}"

%br
= link_to 'Log Out', destroy_user_session_path, method: :delete

app/views/dashboard/show_calendar.erb
<% content_for :for_head do %>
    <%= stylesheet_link_tag    '/stylesheets/show.css', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css" integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js" integrity="sha384-o+RDsa0aLu++PJvFqy8fFScvbHFLtbvScb8AjopnFD+iEQ7wo/CG0xlczd+2O/em" crossorigin="anonymous"></script>
<% end %>

<body>
<%= month_calendar do |date| %>
    <%= date %>
  <% end %>

</body>